apiVersion: apps/v1
kind: Deployment
metadata:
  name: iscsi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iscsi-operator
  template:
    metadata:
      labels:
        name: iscsi-operator
    spec:
      serviceAccountName: iscsi-operator
      containers:
        - name: iscsi-operator
          # Replace this with the built image name
          image: quay.io/example/iscsi-operator
          command:
          - iscsi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "iscsi-operator"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
