// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/utkarshmani1997/iscsi-operator/pkg/apis/openebs/v1alpha1.ISCSIConnection":       schema_pkg_apis_openebs_v1alpha1_ISCSIConnection(ref),
		"github.com/utkarshmani1997/iscsi-operator/pkg/apis/openebs/v1alpha1.ISCSIConnectionSpec":   schema_pkg_apis_openebs_v1alpha1_ISCSIConnectionSpec(ref),
		"github.com/utkarshmani1997/iscsi-operator/pkg/apis/openebs/v1alpha1.ISCSIConnectionStatus": schema_pkg_apis_openebs_v1alpha1_ISCSIConnectionStatus(ref),
	}
}

func schema_pkg_apis_openebs_v1alpha1_ISCSIConnection(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ISCSIConnection is the Schema for the iscsiconnections API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/utkarshmani1997/iscsi-operator/pkg/apis/openebs/v1alpha1.ISCSIConnectionSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/utkarshmani1997/iscsi-operator/pkg/apis/openebs/v1alpha1.ISCSIConnectionStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/utkarshmani1997/iscsi-operator/pkg/apis/openebs/v1alpha1.ISCSIConnectionSpec", "github.com/utkarshmani1997/iscsi-operator/pkg/apis/openebs/v1alpha1.ISCSIConnectionStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_openebs_v1alpha1_ISCSIConnectionSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ISCSIConnectionSpec defines the desired state of ISCSIConnection",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_openebs_v1alpha1_ISCSIConnectionStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ISCSIConnectionStatus defines the observed state of ISCSIConnection",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
