// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIConnection) DeepCopyInto(out *ISCSIConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIConnection.
func (in *ISCSIConnection) DeepCopy() *ISCSIConnection {
	if in == nil {
		return nil
	}
	out := new(ISCSIConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ISCSIConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIConnectionList) DeepCopyInto(out *ISCSIConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ISCSIConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIConnectionList.
func (in *ISCSIConnectionList) DeepCopy() *ISCSIConnectionList {
	if in == nil {
		return nil
	}
	out := new(ISCSIConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ISCSIConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIConnectionSpec) DeepCopyInto(out *ISCSIConnectionSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIConnectionSpec.
func (in *ISCSIConnectionSpec) DeepCopy() *ISCSIConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ISCSIConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIConnectionStatus) DeepCopyInto(out *ISCSIConnectionStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIConnectionStatus.
func (in *ISCSIConnectionStatus) DeepCopy() *ISCSIConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ISCSIConnectionStatus)
	in.DeepCopyInto(out)
	return out
}
